AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Order Processing App with Step Functions and Lambda (Python)

Globals:
  Function:
    Timeout: 10
    Runtime: python3.13

Resources:

  StartOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/start_order/
      Handler: app.lambda_handler
      Layers: 
        - arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPythonV3-python310-x86_64:15
        - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p310-requests:19
      Tags:
        Name: Start_Order
      AutoPublishAlias: Prod
      AutoPublishAliasAllProperties: true

      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /order
            Method: post
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref OrderStateMachine
      Policies: 
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource: !Ref OrderStateMachine
  StartOrderFunctionQA:
    Type: AWS::Lambda::Alias
    Properties:
      Name: QA
      FunctionName: !Ref StartOrderFunction
      FunctionVersion: !GetAtt StartOrderFunction.Version.Version

  ValidateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/validate_order/
      Handler: app.lambda_handler
      Layers: 
        - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p310-requests:19
        - arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPythonV3-python310-x86_64:15
        - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:sample_layer_powertools:15"
      Tags:
        Name: OrderApp
      AutoPublishAlias: Prod
      AutoPublishAliasAllProperties: true
  ValidateOrderFunctionQA:
    Type: AWS::Lambda::Alias
    Properties:
      Name: QA
      FunctionName: !Ref ValidateOrderFunction
      FunctionVersion: !GetAtt ValidateOrderFunction.Version.Version

  ChargePaymentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/charge_payment/
      Handler: app.lambda_handler
      Layers:
        - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p310-numpy:16
        - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p310-pandas:24
      Tags:
        Name: PaymentFunction
      AutoPublishAlias: Prod
      AutoPublishAliasAllProperties: true
  ChargePaymentFunctionQA:
    Type: AWS::Lambda::Alias
    Properties:
      Name: QA
      FunctionName: !Ref ChargePaymentFunction
      FunctionVersion: !GetAtt ChargePaymentFunction.Version.Version

  SendConfirmationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/send_confirmation/
      Handler: app.lambda_handler
      Layers:
        - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p310-numpy:16
        - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p310-pandas:24
        - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:sample_layer_powertools:15"
      Tags:
        Name: SendConformationFunction
      AutoPublishAlias: Prod
      AutoPublishAliasAllProperties: true
  SendConfirmationFunctionQA:
    Type: AWS::Lambda::Alias
    Properties:
      Name: QA
      FunctionName: !Ref SendConfirmationFunction
      FunctionVersion: !GetAtt SendConfirmationFunction.Version.Version

  VerifyUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/verify_user/
      Handler: app.lambda_handler
      Events:
        ApiVerify:
          Type: Api
          Properties:
            Path: /verify
            Method: post
      AutoPublishAlias: Prod
      AutoPublishAliasAllProperties: true
  VerifyUserFunctionQA:
    Type: AWS::Lambda::Alias
    Properties:
      Name: QA
      FunctionName: !Ref VerifyUserFunction
      FunctionVersion: !GetAtt VerifyUserFunction.Version.Version

  OrderStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state_machine/workflow.asl.json
      DefinitionSubstitutions:
        ValidateOrderFunction: !GetAtt ValidateOrderFunction.Arn
        ChargePaymentFunction: !GetAtt ChargePaymentFunction.Arn
        SendConfirmationFunction: !GetAtt SendConfirmationFunction.Arn
      Role: !GetAtt StepFunctionRole.Arn
      Tags:
        Name: SampleStepFunction

  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/order"
